"""Checks for the K4 gaps that the crib-constraint engine left open.

Each gap in ``docs/analysis/K4_NEGATIVE_SPACE.md`` was open because the 24 crib letters
alone can't pin the family down. Every check here adds the one assumption that makes the
family testable, says what that assumption is, and has a planted-solution test.

- ``running_key_english``: a running key from *any* English text (not a known one). The
  key letters at the two crib runs (13 and 11 consecutive letters) would then be English
  fragments themselves. Scored with a real n-gram model against English and random.
- ``transposition_running_key_english``: the same, after every columnar transposition.
- ``recurrence_key``: keys longer than any period, generated by a linear recurrence
  K[i] = c1*K[i-1] + ... + cn*K[i-n] + d (mod 26); Gromark and Fibonacci keys are cases.
- ``general_alphabet_periodic``: a periodic key after an *arbitrary* monoalphabetic step on
  either side. This models letter-swap masking and any mixed alphabet, not just keyword ones.
- ``dial_key_scan``: a key read from a dial (clock face, compass, 24-hour ring) that advances
  a fixed step per letter.
- ``bearing_route_scan``: the text read off a grid along a compass bearing, every whole
  degree, with a periodic key: the "route driven by the compass-rose bearing" for any bearing.
- ``hill_exhaustive``: Hill 4x4 (every matrix consistent with the cribs, decrypted and scored)
  and Hill 5x5 (row by row).
- ``reconstruction_suite``: every family above and in ``crib_constraints`` run against the
  solvekryptos.com reconstruction of the full plaintext, as if all 97 letters were known.
"""

from __future__ import annotations

import itertools
import math
import random
from collections.abc import Iterable
from typing import Any

import numpy as np

from .crib_constraints import (
    STANDARD,
    _scan_mappings,
    _solvable_mod_prime,
    crib_letters,
    families,
    key_values,
    keyed_alphabet,
)
from .english_model import calibration, english_z, mean_logp, reference_english
from .physical_grid import K4

# ── Running key from an unknown English text ────────────────────────────────


def _runs(positions: Iterable[int]) -> list[list[int]]:
    runs: list[list[int]] = []
    for i in sorted(positions):
        if runs and i == runs[-1][-1] + 1:
            runs[-1].append(i)
        else:
            runs.append([i])
    return runs


def _pair_score(texts: list[str]) -> float:
    """Length-weighted mean of english_z over several fragments."""
    total = sum(len(t) for t in texts)
    return sum(english_z(t) * len(t) for t in texts) / total


def running_key_english(
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    keyword: str = "KRYPTOS",
    samples: int = 2000,
    seed: int = 0,
) -> dict[str, Any]:
    """Would the key letters at the crib runs pass as English text?

    For each family, the key letters over each consecutive crib run are scored with
    ``english_z``. ``p_english`` is the share of real English fragment pairs (same lengths,
    independent positions) that score at or below the observed value: small means a running
    key taken from English text is implausible for that family.
    """
    plain = plain if plain is not None else crib_letters()
    runs = [r for r in _runs(plain) if len(r) >= 4]
    lengths = [len(r) for r in runs]
    rng = random.Random(seed)
    eng = reference_english()
    ref = []
    for _ in range(samples):
        frags = []
        for n in lengths:
            s = rng.randrange(0, len(eng) - n)
            frags.append(eng[s : s + n])
        ref.append(_pair_score(frags))
    ref.sort()
    out: dict[str, Any] = {"runs": [[r[0], r[-1]] for r in runs], "families": {}}
    for name, (alpha, fn) in families(keyword).items():
        kv = key_values(alpha, fn, ciphertext, plain)
        # A running key is read in the standard alphabet for the direct families and in the
        # keyed alphabet for the Quagmire ones (key letter = alphabet[key value]).
        key_alpha = alpha if name.startswith("quagmire") else STANDARD
        frags = ["".join(key_alpha[kv[i]] for i in r) for r in runs]
        score = _pair_score(frags)
        p_eng = sum(1 for v in ref if v <= score) / len(ref)
        out["families"][name] = {"key_fragments": frags, "score": round(score, 3), "p_english": p_eng}
    return out


def _gram_index(n: int = 4) -> np.ndarray:
    """Dense log10 table over all 26**n grams (unseen grams get the floor)."""
    from .english_model import table

    grams, floor = table(n)
    arr = np.full(26**n, floor, dtype=np.float32)
    for g, v in grams.items():
        idx = 0
        for ch in g:
            idx = idx * 26 + STANDARD.index(ch)
        arr[idx] = v
    return arr


def _batch_mean_logp(vals: np.ndarray, runs: list[np.ndarray], table4: np.ndarray) -> np.ndarray:
    """Mean quadgram log10 probability per row, over the given column runs."""
    total = np.zeros(vals.shape[0], dtype=np.float64)
    count = 0
    for cols in runs:
        v = vals[:, cols].astype(np.int64)
        idx = v[:, :-3] * 17576 + v[:, 1:-2] * 676 + v[:, 2:-1] * 26 + v[:, 3:]
        total += table4[idx].sum(axis=1)
        count += idx.shape[1]
    return total / count


def transposition_running_key_english(
    widths: Iterable[int] = range(2, 9),
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    keyword: str = "KRYPTOS",
    controls: int = 5,
    seed: int = 0,
) -> dict[str, Any]:
    """Columnar transposition + a running key from any English text, either layer order.

    For every column order, the key letters at the crib runs are scored by quadgram model;
    the best row is compared with the best row for ``controls`` shuffled ciphertexts (the
    multiple-testing baseline). A real hit would sit well above the control maxima.
    """
    from .crib_constraints import _columnar_pt_to_ct

    plain = plain if plain is not None else crib_letters()
    positions = np.array(sorted(plain))
    col_of = {p: j for j, p in enumerate(sorted(plain))}
    runs = [np.array([col_of[i] for i in r]) for r in _runs(plain) if len(r) >= 4]
    table4 = _gram_index(4)
    rng = random.Random(seed)
    texts = [ciphertext] + ["".join(rng.sample(ciphertext, len(ciphertext))) for _ in range(controls)]
    fams = families(keyword)
    out: dict[str, Any] = {}
    for w in widths:
        perms = np.array(list(itertools.permutations(range(w))), dtype=np.int16)
        start = _columnar_pt_to_ct(w, perms, len(ciphertext))
        cpos = start[:, positions % w] + positions // w
        per_w: dict[str, Any] = {}
        for model in ("sub_then_trans", "trans_then_sub"):
            best: dict[str, list[float]] = {}
            for text in texts:
                for name, (alpha, fn) in fams.items():
                    cv = np.array([alpha.index(ch) for ch in text])
                    pv = np.array([alpha.index(plain[i]) for i in sorted(plain)])
                    if model == "sub_then_trans":
                        c_at = cv[cpos]  # key applied at the plaintext position, before transposing
                    else:
                        # trans_then_sub: key runs along the ciphertext; the crib letter t sits at
                        # ciphertext position cpos[:, t], so the key letters there are not a run.
                        # Score the key in ciphertext order instead: sort each row by position.
                        c_at = cv[cpos]
                    kv = np.vectorize(fn)(c_at, pv[None, :])
                    if name.startswith("quagmire"):
                        ka = np.array([STANDARD.index(ch) for ch in alpha])
                        kv = ka[kv]
                    if model == "trans_then_sub":
                        order = np.argsort(cpos, axis=1)
                        kv = np.take_along_axis(kv, order, axis=1)
                        sorted_pos = np.take_along_axis(cpos, order, axis=1)
                        scores = _scattered_runs_score(kv, sorted_pos, table4)
                    else:
                        scores = _batch_mean_logp(kv, runs, table4)
                    best.setdefault(name, []).append(float(scores.max()))
            per_w[model] = {
                name: {"k4_best": round(v[0], 3), "control_best": [round(x, 3) for x in v[1:]]}
                for name, v in best.items()
            }
        out[w] = {"permutations": len(perms), **per_w}
    lo, hi = calibration(13), calibration(11)
    out["reference_mean_logp"] = {"random": round((lo[0] + hi[0]) / 2, 3), "english": round((lo[1] + hi[1]) / 2, 3)}
    return out


def _scattered_runs_score(kv: np.ndarray, pos: np.ndarray, table4: np.ndarray) -> np.ndarray:
    """Mean quadgram log10 over every 4 consecutive ciphertext positions that are all crib positions."""
    rows, n = kv.shape
    total = np.zeros(rows)
    count = np.zeros(rows)
    for t in range(n - 3):
        ok = pos[:, t + 3] - pos[:, t] == 3
        idx = kv[:, t] * 17576 + kv[:, t + 1] * 676 + kv[:, t + 2] * 26 + kv[:, t + 3]
        total += np.where(ok, table4[idx], 0.0)
        count += ok
    return np.where(count > 0, total / np.maximum(count, 1), -99.0)


# ── Linear-recurrence keys ─────────────────────────────────────────────────


def recurrence_key(
    max_order: int = 7,
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    keyword: str = "KRYPTOS",
) -> dict[str, list[dict[str, int]]]:
    """K[i] = c1*K[i-1] + ... + cn*K[i-n] + d (mod 26), any coefficients, any primer.

    Every window of n+1 consecutive crib positions gives one linear equation in the n+1
    unknowns (c1..cn, d). K4's two crib runs (13 and 11 letters) give 24 - 2n equations, so
    orders up to 7 are overdetermined. Solvable over Z26 iff solvable over GF(2) and GF(13).
    Returns the (order, equations) pairs that stay consistent.
    """
    plain = plain if plain is not None else crib_letters()
    out: dict[str, list[dict[str, int]]] = {}
    for name, (alpha, fn) in families(keyword).items():
        kv = key_values(alpha, fn, ciphertext, plain)
        hits = []
        for n in range(1, max_order + 1):
            rows, rhs = [], []
            for i in kv:
                if all(i - j in kv for j in range(1, n + 1)):
                    rows.append([kv[i - j] for j in range(1, n + 1)] + [1])
                    rhs.append(kv[i])
            if len(rows) <= n + 1:
                continue
            if _solvable_mod_prime(rows, rhs, 2) and _solvable_mod_prime(rows, rhs, 13):
                hits.append({"order": n, "equations": len(rows)})
        out[name] = hits
    return out


def recurrence_testable_orders(plain: dict[int, str] | None = None, max_order: int = 12) -> list[int]:
    """Orders with more equations than unknowns for these crib positions."""
    plain = plain if plain is not None else crib_letters()
    pos = set(plain)
    return [
        n for n in range(1, max_order + 1) if sum(1 for i in pos if all(i - j in pos for j in range(1, n + 1))) > n + 1
    ]


# ── Arbitrary monoalphabetic step + periodic key ───────────────────────────


class _PotentialUnionFind:
    """Union-find carrying value differences mod 26: tracks val(x) - val(root)."""

    def __init__(self) -> None:
        self.parent: dict[str, str] = {}
        self.pot: dict[str, int] = {}

    def find(self, x: str) -> tuple[str, int]:
        if x not in self.parent:
            self.parent[x], self.pot[x] = x, 0
            return x, 0
        path = []
        while self.parent[x] != x:
            path.append(x)
            x = self.parent[x]
        root, acc = x, 0
        for node in reversed(path):
            acc = (acc + self.pot[node]) % 26
            self.pot[node] = acc
            self.parent[node] = root
        return root, self.pot[path[0]] if path else 0

    def union(self, a: str, b: str, diff: int) -> bool:
        """Impose val(a) - val(b) = diff. False if it contradicts earlier constraints."""
        ra, pa = self.find(a)
        rb, pb = self.find(b)
        if ra == rb:
            return (pa - pb) % 26 == diff % 26
        # val(a) = pa + v(ra), val(b) = pb + v(rb) -> v(ra) - v(rb) = diff - pa + pb
        self.parent[ra] = rb
        self.pot[ra] = (diff - pa + pb) % 26
        return True


def _alphabet_system_consistent(edges: list[tuple[str, str, int]], letters_prefix: str) -> bool:
    uf = _PotentialUnionFind()
    for a, b, d in edges:
        if not uf.union(a, b, d):
            return False
    # Bijection: two different letters in one component must get different values.
    seen: dict[tuple[str, int], str] = {}
    for a, _b, _d in edges:
        if not a.startswith(letters_prefix):
            continue
        root, pot = uf.find(a)
        other = seen.setdefault((root, pot), a)
        if other != a:
            return False
    return True


def general_alphabet_periodic(
    max_period: int = 26,
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
) -> dict[str, list[int]]:
    """Periodic key combined with an arbitrary (not keyword-built) alphabet on one side.

    - ``mixed_plain_alphabet``: C = s(P) + k[i mod p], s any bijection. Also covers Beaufort
      and variant forms and any letter-swap or phonetic masking that is letter-for-letter
      consistent, because those are all just a different s.
    - ``mixed_cipher_alphabet``: C = t(P + k[i mod p]) or t(k[i mod p] - P), t any bijection.

    The unknowns are the alphabet's values and the key, linked by difference equations mod
    26 and solved exactly with a union-find. Returns the consistent periods. With 13 distinct
    crib plaintext letters (or 17 ciphertext letters) plus p key slots and 24 equations, the
    test has teeth only for small p; ``testable_periods`` in the result says where.
    """
    plain = plain if plain is not None else crib_letters()
    items = sorted(plain.items())
    ci = {i: STANDARD.index(ciphertext[i]) for i, _ in items}
    pi = {i: STANDARD.index(p) for i, p in items}
    out: dict[str, list[int]] = {
        "mixed_plain_alphabet": [],
        "mixed_cipher_alphabet_add": [],
        "mixed_cipher_alphabet_sub": [],
    }
    for p in range(1, max_period + 1):
        # s(P) - (-k[r]) = C
        edges = [(f"P{plain[i]}", f"K{i % p}", ci[i]) for i, _ in items]
        if _alphabet_system_consistent(edges, "P"):
            out["mixed_plain_alphabet"].append(p)
        # t^-1(C) - k[r] = P
        edges = [(f"C{ciphertext[i]}", f"K{i % p}", pi[i]) for i, _ in items]
        if _alphabet_system_consistent(edges, "C"):
            out["mixed_cipher_alphabet_add"].append(p)
        # t^-1(C) = k[r] - P  ->  t^-1(C) - k[r] = -P
        edges = [(f"C{ciphertext[i]}", f"K{i % p}", -pi[i]) for i, _ in items]
        if _alphabet_system_consistent(edges, "C"):
            out["mixed_cipher_alphabet_sub"].append(p)
    return out


def general_alphabet_control_rate(period: int, trials: int = 200, seed: int = 0) -> float:
    """Share of random ciphertexts (same cribs) that pass ``mixed_plain_alphabet`` at ``period``."""
    rng = random.Random(seed)
    hits = 0
    for _ in range(trials):
        ct = "".join(rng.choice(STANDARD) for _ in range(len(K4)))
        hits += period in general_alphabet_periodic(max_period=period, ciphertext=ct)["mixed_plain_alphabet"]
    return hits / trials


# ── Dial keys (clock face, compass, 24-hour ring) ──────────────────────────

DIALS: dict[str, int] = {
    "12-hour face": 12,
    "24-hour ring (Weltzeituhr)": 24,
    "minutes / seconds": 60,
    "compass degrees": 360,
    "12-hour face in minutes": 720,
    "24-hour ring in minutes": 1440,
}


def dial_key_scan(
    dials: dict[str, int] | None = None,
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    keyword: str = "KRYPTOS",
) -> dict[str, dict[str, list[dict[str, int]]]]:
    """Key read from a dial that advances ``step`` positions per letter from ``start``.

    Reading at letter i: r = (start + step * i) mod N. Two rules turn a reading into a key value:
    ``scaled`` = floor(r * 26 / N) + b and ``mod26`` = r + b (mod 26), with any offset b.
    Exhaustive over every start, step and offset for each dial size N.
    """
    dials = dials if dials is not None else DIALS
    plain = plain if plain is not None else crib_letters()
    pos = np.array(sorted(plain), dtype=np.int64)
    out: dict[str, dict[str, list[dict[str, int]]]] = {}
    for name, (alpha, fn) in families(keyword).items():
        kv = np.array([v for _, v in sorted(key_values(alpha, fn, ciphertext, plain).items())], dtype=np.int64)
        hits: dict[str, list[dict[str, int]]] = {}
        for label, n in dials.items():
            found = []
            steps = np.arange(n, dtype=np.int64)
            for start in range(n):
                r = (start + steps[:, None] * pos[None, :]) % n  # (steps, cribs)
                for rule in ("scaled", "mod26"):
                    v = (r * 26) // n if rule == "scaled" else r % 26
                    diff = (kv[None, :] - v) % 26
                    ok = np.all(diff == diff[:, :1], axis=1)
                    for s in np.flatnonzero(ok)[:5]:
                        found.append({"start": start, "step": int(s), "rule": rule, "offset": int(diff[s, 0])})
            hits[label] = found
        out[name] = hits
    return out


# ── Routes along a compass bearing ─────────────────────────────────────────


def bearing_route(n: int, width: int, bearing_deg: float) -> list[int]:
    """Cell order for reading an n-letter text written in rows of ``width`` along a bearing.

    Lines run in the bearing's direction (0 = up the page, 90 = right). Cells are grouped into
    parallel lines by their perpendicular offset (scaled so axis and diagonal bearings give
    rows, columns and diagonals exactly), lines taken left to right across the bearing, each
    line read in the bearing's direction.
    """
    th = math.radians(bearing_deg)
    dx, dy = math.sin(th), -math.cos(th)  # screen coords: row index increases downward
    spacing = max(abs(dx), abs(dy))
    cells = []
    for i in range(n):
        r, c = divmod(i, width)
        along = c * dx + r * dy
        across = -c * dy + r * dx
        cells.append((round(across / spacing), round(along, 6), i))
    return [i for _, _, i in sorted(cells)]


def bearing_route_mappings(
    n: int = 97, widths: Iterable[int] = range(4, 25), step_deg: float = 1.0
) -> tuple[list[list[int]], list[dict[str, Any]]]:
    """Distinct bearing routes (and their inverses) over the widths and bearings given."""
    seen: set[tuple[int, ...]] = set()
    maps, labels = [], []
    deg = 0.0
    bearings = []
    while deg < 360:
        bearings.append(round(deg, 3))
        deg += step_deg
    for w in widths:
        for b in bearings:
            route = bearing_route(n, w, b)
            inv = [0] * n
            for j, i in enumerate(route):
                inv[i] = j
            for direction, perm in (("read_along", inv), ("write_along", route)):
                key = tuple(perm)
                if key in seen:
                    continue
                seen.add(key)
                maps.append(perm)
                labels.append({"width": w, "bearing": b, "direction": direction})
    return maps, labels


def bearing_route_scan(
    widths: Iterable[int] = range(4, 25),
    periods: Iterable[int] = range(1, 23),
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    keyword: str = "KRYPTOS",
    step_deg: float = 1.0,
) -> dict[str, Any]:
    """Bearing routes composed with a periodic key, either layer order.

    ``perm[i]`` is the ciphertext position that holds plaintext letter i.
    """
    plain = plain if plain is not None else crib_letters()
    maps, labels = bearing_route_mappings(len(ciphertext), widths, step_deg)
    positions = sorted(plain)
    cpos = np.array([[m[i] for i in positions] for m in maps], dtype=np.int64)
    return {"mappings": len(maps), **_scan_mappings(cpos, labels, ciphertext, plain, list(periods), keyword, 5)}


# ── Long keys spelled from the Kryptos vocabulary ─────────────────────────


def vocabulary_phrase_keys(
    words: Iterable[str] | None = None,
    max_words: int = 3,
    min_len: int = 27,
    max_len: int = 60,
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    keyword: str = "KRYPTOS",
) -> dict[str, Any]:
    """Keys longer than the cribs can pin down, spelled by chaining 2-3 Kryptos words.

    A key like PALIMPSESTABSCISSAKRYPTOS repeated with period len(phrase) is fully known, so
    every crib letter checks it directly, at every starting offset. Covers ordered phrases
    of up to ``max_words`` words from ``crib_constraints.KRYPTOS_VOCABULARY`` whose length
    is in [min_len, max_len]. Returns the number of phrases tested and any that fit.
    """
    from .crib_constraints import KRYPTOS_VOCABULARY

    words = sorted({w.upper() for w in (words or KRYPTOS_VOCABULARY)})
    plain = plain if plain is not None else crib_letters()
    fams = {name: (alpha, key_values(alpha, fn, ciphertext, plain)) for name, (alpha, fn) in families(keyword).items()}
    tested, hits = 0, []
    for k in range(2, max_words + 1):
        for combo in itertools.product(words, repeat=k):
            phrase = "".join(combo)
            if not min_len <= len(phrase) <= max_len:
                continue
            tested += 1
            n = len(phrase)
            for name, (alpha, kv) in fams.items():
                kvals = [alpha.index(ch) for ch in phrase]
                for off in range(n):
                    if all(kvals[(i + off) % n] == v for i, v in kv.items()):
                        hits.append({"phrase": phrase, "family": name, "offset": off})
    return {"phrases_tested": tested, "hits": hits}


# ── Wide columnar transpositions by backtracking ───────────────────────────


def _columnar_backtrack(
    width: int,
    period: int,
    model: str,
    alpha: str,
    fn: Any,
    ciphertext: str,
    plain: dict[int, str],
    max_solutions: int,
) -> tuple[list[list[int]], int, bool]:
    """Column orders consistent with a periodic key, found by depth-first search.

    Columns are placed in reading order; placing a column fixes the ciphertext position of
    every crib letter in it, so its key value and key slot are known and checked at once.
    Returns (orders, nodes visited, truncated).
    """
    n = len(ciphertext)
    col_len = [(n - c + width - 1) // width for c in range(width)]
    cribs_in = [
        [(j // width, j, alpha.index(p)) for j, p in sorted(plain.items()) if j % width == c] for c in range(width)
    ]
    cidx = [alpha.index(ch) for ch in ciphertext]
    slots: dict[int, int] = {}
    used = [False] * width
    order: list[int] = []
    found: list[list[int]] = []
    nodes = 0
    sub_first = model == "sub_then_trans"

    def rec(offset: int) -> bool:
        nonlocal nodes
        nodes += 1
        if len(order) == width:
            found.append(list(order))
            return len(found) >= max_solutions
        for c in range(width):
            if used[c]:
                continue
            added = []
            ok = True
            for r, j, pv in cribs_in[c]:
                cp = offset + r
                k = fn(cidx[cp], pv)
                s = j % period if sub_first else cp % period
                have = slots.get(s)
                if have is None:
                    slots[s] = k
                    added.append(s)
                elif have != k:
                    ok = False
                    break
            if ok:
                used[c] = True
                order.append(c)
                if rec(offset + col_len[c]):
                    return True
                used[c] = False
                order.pop()
            for s in added:
                del slots[s]
        return False

    truncated = rec(0)
    return found, nodes, truncated


def _decrypt_columnar_periodic(
    order: list[int], width: int, period: int, alpha: str, fn: Any, ciphertext: str, plain: dict[int, str]
) -> str | None:
    """Full decryption for a sub-then-transpose survivor when the cribs fix every key slot."""
    n = len(ciphertext)
    col_len = [(n - c + width - 1) // width for c in range(width)]
    start, off = {}, 0
    for c in order:
        start[c], off = off, off + col_len[c]
    key = {}
    for j, ch in plain.items():
        key[j % period] = fn(alpha.index(ciphertext[start[j % width] + j // width]), alpha.index(ch))
    if len(key) < period:
        return None
    inverse = {(cv, k): pv for cv in range(26) for pv in range(26) for k in [fn(cv, pv)]}
    out = []
    for j in range(n):
        cv = alpha.index(ciphertext[start[j % width] + j // width])
        out.append(alpha[inverse[(cv, key[j % period])]])
    return "".join(out)


def wide_columnar_scan(
    widths: Iterable[int] = range(10, 13),
    periods: Iterable[int] = range(1, 23),
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    keyword: str = "KRYPTOS",
    max_solutions: int = 20_000,
) -> dict[int, Any]:
    """Columnar widths beyond brute force (10! and up) + periodic key, either order, exactly.

    Depth-first search over column orders with crib-key pruning; gives the same survivors as
    ``crib_constraints.columnar_period_scan`` where both run. Survivors whose cribs fix every key
    slot (sub-then-transpose, period <= 17 for K4) are decrypted in full and scored with
    ``english_z``: a real solution reads as English (about 1), chance survivors as noise.
    """
    plain = plain if plain is not None else crib_letters()
    out: dict[int, Any] = {}
    for w in widths:
        per_model: dict[str, Any] = {}
        for model in ("sub_then_trans", "trans_then_sub"):
            per_family: dict[str, Any] = {}
            for name, (alpha, fn) in families(keyword).items():
                per_period = {}
                for p in periods:
                    orders, nodes, truncated = _columnar_backtrack(
                        w, p, model, alpha, fn, ciphertext, plain, max_solutions
                    )
                    entry: dict[str, Any] = {"survivors": len(orders), "nodes": nodes, "truncated": truncated}
                    if orders and model == "sub_then_trans":
                        scores = [
                            english_z(_noncrib_text(t, plain))
                            for t in (
                                _decrypt_columnar_periodic(o, w, p, alpha, fn, ciphertext, plain) for o in orders[:500]
                            )
                            if t is not None
                        ]
                        if scores:
                            entry["best_english_z"] = round(max(scores), 3)
                    if orders:
                        entry["examples"] = orders[:3]
                    per_period[p] = entry
                per_family[name] = per_period
            per_model[model] = per_family
        out[w] = per_model
    return out


# ── Hill 4x4 and 5x5 ────────────────────────────────────────────────────────


def _det_mod(m: np.ndarray, q: int) -> int:
    a = [[int(x) % q for x in row] for row in m]
    n, det = len(a), 1
    for c in range(n):
        p = next((r for r in range(c, n) if a[r][c]), None)
        if p is None:
            return 0
        if p != c:
            a[c], a[p] = a[p], a[c]
            det = -det
        det = det * a[c][c] % q
        inv = pow(a[c][c], q - 2, q)
        for r in range(c + 1, n):
            f = a[r][c] * inv % q
            a[r] = [(x - f * y) % q for x, y in zip(a[r], a[c], strict=True)]
    return det % q


def _invertible_mod26(m: np.ndarray) -> bool:
    return _det_mod(m, 2) != 0 and _det_mod(m, 13) != 0


def _row_solutions(n: int, blocks_c: np.ndarray, targets: np.ndarray) -> np.ndarray:
    """All rows x in Z26^n with blocks_c @ x == targets (mod 26), by exhaustive search."""
    sols = []
    grid = np.array(list(itertools.product(range(26), repeat=n - 1)), dtype=np.int64) if n > 1 else None
    for first in range(26):
        x = np.concatenate([np.full((len(grid), 1), first), grid], axis=1)
        ok = np.all((x @ blocks_c.T) % 26 == targets[None, :], axis=1)
        sols.append(x[ok])
    return np.concatenate(sols) if sols else np.zeros((0, n), dtype=np.int64)


def _noncrib_text(text: str, plain: dict[int, str]) -> str:
    return "".join(ch for i, ch in enumerate(text) if i not in plain)


def hill_exhaustive(
    sizes: Iterable[int] = (4,),
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    max_matrices: int = 200_000,
) -> dict[int, list[dict[str, Any]]]:
    """Every Hill matrix consistent with the crib blocks, decrypted and scored.

    Decryption is P = K C blockwise (K invertible mod 26; this also covers C = M P with
    K = M^-1). Each row of K is solved separately by exhaustive search over Z26^n. For n = 4
    the four crib blocks leave only a handful of rows, so every full matrix is decrypted and
    the non-crib text scored with ``english_z``. Reports, per alignment, how many invertible
    matrices exist and the best score. A true key would score like English (about 1).
    """
    plain = plain if plain is not None else crib_letters()
    cv = np.array([STANDARD.index(c) for c in ciphertext])
    out: dict[int, list[dict[str, Any]]] = {}
    for n in sizes:
        res = []
        for offset in range(n):
            blocks = [b for b in range(offset, len(ciphertext) - n + 1, n) if all(i in plain for i in range(b, b + n))]
            if len(blocks) < n - 1:
                res.append({"offset": offset, "blocks": len(blocks), "status": "too few blocks"})
                continue
            bc = np.array([[cv[i] for i in range(b, b + n)] for b in blocks])
            row_sols = []
            for r in range(n):
                t = np.array([STANDARD.index(plain[b + r]) for b in blocks])
                row_sols.append(_row_solutions(n, bc, t))
            combos = math.prod(len(s) for s in row_sols)
            entry: dict[str, Any] = {
                "offset": offset,
                "blocks": len(blocks),
                "row_solutions": [len(s) for s in row_sols],
            }
            if combos == 0:
                entry["status"] = "no consistent matrix"
            elif combos > max_matrices:
                entry["status"] = f"{combos} matrices; too many to decrypt one by one"
            else:
                best, invertible = -9.0, 0
                full_blocks = range(offset, len(ciphertext) - n + 1, n)
                for rows in itertools.product(*row_sols):
                    k = np.array(rows)
                    if not _invertible_mod26(k):
                        continue
                    invertible += 1
                    text = [""] * len(ciphertext)
                    for b in full_blocks:
                        pv = (k @ cv[b : b + n]) % 26
                        for j in range(n):
                            text[b + j] = STANDARD[pv[j]]
                    body = _noncrib_text("".join(text), plain)
                    best = max(best, english_z(body))
                entry.update(
                    {"status": "decrypted", "invertible_matrices": invertible, "best_english_z": round(best, 3)}
                )
            res.append(entry)
        out[n] = res
    return out


def hill_rowspace_search(
    n: int = 5,
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    max_matrices: int = 20_000_000,
    top: int = 200,
    chunk: int = 500_000,
) -> list[dict[str, Any]]:
    """Hill n x n where the crib blocks leave a few choices per row: score every matrix.

    For each alignment, every row of K consistent with the crib blocks is found. When the
    number of full matrices is at most ``max_matrices`` (for 5x5 with four crib blocks, 26 per
    row, so 26**5), every matrix is used to decrypt K4 and scored with the quadgram model;
    the ``top`` best are checked for invertibility and their non-crib text scored with
    ``english_z``. A true key would score like English (about 1); K4's best stays near noise.
    """
    plain = plain if plain is not None else crib_letters()
    cv = np.array([STANDARD.index(c) for c in ciphertext])
    table4 = _gram_index(4)
    out = []
    for offset in range(n):
        blocks = [b for b in range(offset, len(ciphertext) - n + 1, n) if all(i in plain for i in range(b, b + n))]
        entry: dict[str, Any] = {"offset": offset, "blocks": len(blocks)}
        if len(blocks) < n - 1:
            out.append({**entry, "status": "too few blocks"})
            continue
        bc = np.array([[cv[i] for i in range(b, b + n)] for b in blocks])
        rows = [fc_row for fc_row in (
            _row_solutions(n, bc, np.array([STANDARD.index(plain[b + r]) for b in blocks])) for r in range(n)
        )]  # fmt: skip
        entry["row_solutions"] = [len(r) for r in rows]
        total = math.prod(len(r) for r in rows)
        if total == 0:
            out.append({**entry, "status": "no consistent matrix"})
            continue
        if total > max_matrices:
            out.append({**entry, "status": f"{total} matrices; above the search limit"})
            continue
        full = np.array([cv[b : b + n] for b in range(offset, len(ciphertext) - n + 1, n)])  # (nb, n)
        letters = [(r @ full.T) % 26 for r in rows]  # per row: (choices, nb)
        sizes = [len(r) for r in rows]
        best_scores: list[tuple[float, tuple[int, ...]]] = []
        for lo in range(0, total, chunk):
            idx = np.arange(lo, min(total, lo + chunk))
            choice = np.stack(np.unravel_index(idx, sizes), axis=1)  # (m, n)
            text = np.stack([letters[r][choice[:, r]] for r in range(n)], axis=2).reshape(len(idx), -1)
            q = text[:, :-3] * 17576 + text[:, 1:-2] * 676 + text[:, 2:-1] * 26 + text[:, 3:]
            score = table4[q].mean(axis=1)
            keep = np.argsort(score)[-top:]
            best_scores += [(float(score[k]), tuple(int(x) for x in choice[k])) for k in keep]
            best_scores = sorted(best_scores)[-top:]
        best_z, invertible = -9.0, 0
        for _, ch in best_scores:
            k = np.array([rows[r][ch[r]] for r in range(n)])
            if not _invertible_mod26(k):
                continue
            invertible += 1
            txt = [""] * len(ciphertext)
            for b in range(offset, len(ciphertext) - n + 1, n):
                pv = (k @ cv[b : b + n]) % 26
                for j in range(n):
                    txt[b + j] = STANDARD[pv[j]]
            best_z = max(best_z, english_z(_noncrib_text("".join(txt), plain)))
        out.append({**entry, "status": "searched", "matrices": total, "invertible_in_top": invertible,
                    "best_english_z": round(best_z, 3)})  # fmt: skip
    return out


def _dense_table(n: int) -> np.ndarray:
    from .english_model import table

    grams, floor = table(n) if n > 2 else _bigram_table()
    arr = np.full(26**n, floor, dtype=np.float32)
    for g, v in grams.items():
        idx = 0
        for ch in g:
            idx = idx * 26 + STANDARD.index(ch)
        arr[idx] = v
    return arr


def _bigram_table() -> tuple[dict[str, float], float]:
    from pathlib import Path

    from kryptos.paths import get_repo_root

    path = Path(get_repo_root()) / "data" / "ngrams" / "english_2grams.tsv"
    grams, floor = {}, -10.0
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# floor"):
            floor = float(line.split("\t")[1])
        elif line and not line.startswith("#"):
            g, v = line.split("\t")
            grams[g] = float(v)
    return grams, floor


def hill_beam_search(
    n: int = 5,
    offsets: Iterable[int] | None = None,
    ciphertext: str = K4,
    plain: dict[int, str] | None = None,
    beam: int = 3000,
) -> list[dict[str, Any]]:
    """Hill n x n where the cribs leave too many matrices to list: build K row by row.

    Row r of K produces plaintext letter r of every block. Rows are added in order and the
    partial texts ranked by the English n-gram model over the letters decided so far (bigrams
    after two rows, trigrams after three, quadgrams after that); the best ``beam`` partial
    matrices survive each step. A heuristic, so the tier is statistical, but a planted key is
    recovered (see tests), and K4's best stays near noise.
    """
    plain = plain if plain is not None else crib_letters()
    cv = np.array([STANDARD.index(c) for c in ciphertext])
    tables = {2: _dense_table(2), 3: _dense_table(3), 4: _dense_table(4)}
    offsets = list(offsets) if offsets is not None else list(range(n))
    out = []
    for offset in offsets:
        blocks = [b for b in range(offset, len(ciphertext) - n + 1, n) if all(i in plain for i in range(b, b + n))]
        full = np.array([cv[b : b + n] for b in range(offset, len(ciphertext) - n + 1, n)])  # (nb, n)
        rows = [
            _row_solutions(n, np.array([[cv[i] for i in range(b, b + n)] for b in blocks]).reshape(len(blocks), n),
                           np.array([STANDARD.index(plain[b + r]) for b in blocks]))
            if blocks else np.array(list(itertools.product(range(26), repeat=n)))
            for r in range(n)
        ]  # fmt: skip
        entry: dict[str, Any] = {"offset": offset, "blocks": len(blocks), "row_solutions": [len(r) for r in rows]}
        if any(len(r) == 0 for r in rows):
            out.append({**entry, "status": "no consistent matrix"})
            continue
        letters = [(r @ full.T) % 26 for r in rows]  # per row: (choices, nb)
        states = [(0.0, (i,)) for i in range(len(rows[0]))]
        for r in range(1, n):
            size = min(r + 1, 4)
            cand_scores, cand_states = [], []
            prev = np.array([s[1] for s in states])  # (S, r)
            for j in range(len(rows[r])):
                cols = [letters[q][prev[:, q]] for q in range(r)] + [
                    np.broadcast_to(letters[r][j], (len(prev), full.shape[0]))
                ]
                window = np.stack(cols[-size:], axis=2)  # (S, nb, size)
                idx = np.zeros(window.shape[:2], dtype=np.int64)
                for t in range(size):
                    idx = idx * 26 + window[:, :, t]
                sc = tables[size][idx].mean(axis=1)
                cand_scores.append(sc)
                cand_states.append(j)
            allsc = np.stack(cand_scores, axis=1)  # (S, J)
            flat = np.argsort(allsc, axis=None)[-beam:]
            si, ji = np.unravel_index(flat, allsc.shape)
            states = [
                (float(allsc[a, b]), tuple(states[a][1]) + (cand_states[b],)) for a, b in zip(si, ji, strict=True)
            ]
        best_z, invertible = -9.0, 0
        for _, choice in sorted(states)[-200:]:
            k = np.array([rows[r][choice[r]] for r in range(n)])
            if not _invertible_mod26(k):
                continue
            invertible += 1
            txt = [""] * len(ciphertext)
            for b in range(offset, len(ciphertext) - n + 1, n):
                pv = (k @ cv[b : b + n]) % 26
                for j in range(n):
                    txt[b + j] = STANDARD[pv[j]]
            best_z = max(best_z, english_z(_noncrib_text("".join(txt), plain)))
        out.append({**entry, "status": "beam", "invertible_in_top": invertible, "best_english_z": round(best_z, 3)})
    return out


# ── The full reconstruction as plaintext ───────────────────────────────────


def reconstruction_plain(candidate: str = "solvekryptos_field_guide") -> dict[int, str]:
    """All 97 letters of a published reconstruction, position -> letter."""
    from .plaintext_evidence import reconstructed_plaintext

    text = reconstructed_plaintext(candidate)
    if text is None:
        raise ValueError(f"no 97-letter reconstruction registered as {candidate!r}")
    return dict(enumerate(text))


def _periodic_consistent(kv: dict[int, int], p: int) -> bool:
    slots: dict[int, int] = {}
    return all(slots.setdefault(i % p, k) == k for i, k in kv.items())


def reconstruction_suite(
    candidate: str = "solvekryptos_field_guide",
    ciphertext: str = K4,
    include_dictionary: bool = False,
    columnar_widths: Iterable[int] = range(2, 9),
) -> dict[str, Any]:
    """Could *any* tested family turn the reconstructed plaintext into K4?

    Uses all 97 letters as known plaintext, so periods up to 48 and more are testable. A
    survivor would be a strong lead (it fits 97 letters, not 24); zero survivors means the
    reconstruction is not the output of that family, whatever the key.
    """
    from . import crib_constraints as cc
    from . import structural_checks as sc

    plain = reconstruction_plain(candidate)
    out: dict[str, Any] = {
        "candidate": candidate,
        "english_z_of_reconstruction": round(english_z("".join(plain.values())), 3),
    }
    periodic = {}
    for name, (alpha, fn) in families().items():
        kv = key_values(alpha, fn, ciphertext, plain)
        periodic[name] = [p for p in range(1, 49) if _periodic_consistent(kv, p)]
    out["periodic_1_48"] = periodic
    out["monoalphabetic_conflicts"] = len(cc.monoalphabetic_conflicts(ciphertext, plain))
    out["ciphertext_autokey"] = {k: v["survivors"] for k, v in cc.ciphertext_autokey(ciphertext, plain).items()}
    out["plaintext_autokey"] = {k: v["survivors"] for k, v in cc.plaintext_autokey(ciphertext, plain).items()}
    out["linear_key"] = cc.linear_key(ciphertext, plain)
    out["progressive_key_1_48"] = cc.progressive_key(ciphertext, plain, periods=range(1, 49))
    out["double_periodic_p_le_45"] = cc.double_periodic_consistency(45, ciphertext, plain)
    out["recurrence_key_1_40"] = recurrence_key(40, ciphertext, plain)
    out["general_alphabet_periodic_1_48"] = general_alphabet_periodic(48, ciphertext, plain)
    out["hill_2_9"] = sc.hill_consistency(range(2, 10), ciphertext, plain)
    out["dial_keys"] = {
        k: {d: len(v) for d, v in fam.items()} for k, fam in dial_key_scan(None, ciphertext, plain).items()
    }
    # Keystream as English: a running key from any English text.
    keystreams = {}
    for name, (alpha, fn) in families().items():
        kv = key_values(alpha, fn, ciphertext, plain)
        key_alpha = alpha if name.startswith("quagmire") else STANDARD
        ks = "".join(key_alpha[kv[i]] for i in range(len(ciphertext)))
        keystreams[name] = {"keystream": ks, "english_z": round(english_z(ks), 3)}
    out["running_key_keystreams"] = keystreams

    def _survivors(scan: dict[str, Any]) -> int:
        return sum(
            v["survivors"]
            for model in ("sub_then_trans", "trans_then_sub")
            for fam in scan[model].values()
            for v in fam.values()
        )

    col = cc.columnar_period_scan(widths=columnar_widths, periods=range(1, 49), ciphertext=ciphertext, plain=plain)
    out["columnar_period_1_48"] = {w: _survivors(r) for w, r in col.items()}
    geo = cc.geometry_period_scan(periods=range(1, 49), ciphertext=ciphertext, plain=plain)
    out["geometry_period_1_48"] = _survivors(geo)
    rot = sc.double_rotation_period_scan(periods=range(1, 49), ciphertext=ciphertext, plain=plain)
    out["double_rotation_period_1_48"] = _survivors(rot)
    out["bearing_route_period_1_48"] = _survivors(
        bearing_route_scan(periods=range(1, 49), ciphertext=ciphertext, plain=plain)
    )
    if include_dictionary:
        _, words = cc.dictionary_source()
        kw = cc.keyword_alphabet_scan(words, periods=range(1, 49), ciphertext=ciphertext, plain=plain)
        out["keyword_alphabets_1_48"] = {
            q: sum(v["survivors"] for v in kw[q].values()) for q in ("quagmire1", "quagmire2", "quagmire3")
        }
        q4 = cc.quagmire4_dictionary_scan(words, periods=range(1, 49), ciphertext=ciphertext, plain=plain)
        out["quagmire4_dictionary_1_48"] = sum(v["survivors"] for v in q4["periods"].values())
    return out


DEFAULT_FRONTIER_ARTIFACT = "K4_FRONTIER_NULL.json"


def run_frontier_suite(
    artifact_path: str | None = DEFAULT_FRONTIER_ARTIFACT,
    heavy: bool = True,
    include_dictionary: bool = False,
) -> dict[str, Any]:
    """Run every frontier check on K4 (and the reconstruction suite), write one artifact.

    ``heavy`` adds the Hill 5x5 search (about a minute), the columnar English running-key
    scan and the reconstruction suite (a few minutes). ``include_dictionary`` adds the
    dictionary Quagmire scans to the reconstruction suite.
    """
    import json
    import os
    import threading
    from datetime import datetime, timezone
    from pathlib import Path

    summary: dict[str, Any] = {
        "status": "complete",
        "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "running_key_english": running_key_english(),
        "recurrence_key": recurrence_key(),
        "general_alphabet_periodic": general_alphabet_periodic(),
        "general_alphabet_control_rate_p12": general_alphabet_control_rate(12, trials=100),
        "dial_keys": {k: {d: len(v) for d, v in fam.items()} for k, fam in dial_key_scan().items()},
        "bearing_routes": _route_survivors(bearing_route_scan()),
        "hill_4x4": hill_exhaustive((4,))[4],
        "vocabulary_phrase_keys": vocabulary_phrase_keys(),
    }
    if heavy:
        summary["hill_5x5"] = hill_rowspace_search(5)
        wide = wide_columnar_scan(widths=range(10, 12))
        summary["wide_columnar_10_11"] = {
            w: {m: sum(e["survivors"] for fam in r[m].values() for e in fam.values()) for m in r}
            for w, r in wide.items()
        }
        summary["columnar_running_key_english"] = transposition_running_key_english()
        summary["reconstruction"] = reconstruction_suite(include_dictionary=include_dictionary)
    if artifact_path:
        path = Path(artifact_path)
        tmp = path.with_name(f"{path.name}.{os.getpid()}.{threading.get_ident()}.tmp")
        tmp.write_text(json.dumps(summary, indent=2, default=str))
        os.replace(tmp, path)
    return summary


def _route_survivors(scan: dict[str, Any]) -> dict[str, Any]:
    return {
        "mappings": scan["mappings"],
        "survivors": sum(
            v["survivors"] for model in ("sub_then_trans", "trans_then_sub") for fam in scan[model].values()
            for v in fam.values()
        ),
    }  # fmt: skip


__all__ = [
    "DIALS",
    "bearing_route",
    "bearing_route_mappings",
    "bearing_route_scan",
    "dial_key_scan",
    "general_alphabet_control_rate",
    "general_alphabet_periodic",
    "hill_beam_search",
    "hill_rowspace_search",
    "hill_exhaustive",
    "keyed_alphabet",
    "mean_logp",
    "reconstruction_plain",
    "reconstruction_suite",
    "run_frontier_suite",
    "recurrence_key",
    "recurrence_testable_orders",
    "running_key_english",
    "transposition_running_key_english",
    "vocabulary_phrase_keys",
    "wide_columnar_scan",
]
