name: CI (fast)

on:
  push:
    branches: [ main, autopilot/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
          # install the package in editable mode so package imports resolve
          pip install -e .
      - name: Verify package installation
        run: |
          python -c "from kryptos.agents import OpsAgent, QAgent, SpyAgent; print('✓ Agents imported successfully')"
      - name: Run tests
        run: pytest -q
