name: CI (fast)

on:
  push:
    branches: [ main, autopilot/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
          # install the package in editable mode so package imports resolve
          pip install -e .
      - name: Download spaCy model
        run: |
          python -m spacy download en_core_web_sm
      - name: Debug package structure
        run: |
          echo "=== Python version ==="
          python --version
          echo "=== Package location ==="
          python -c "import sys; print('\n'.join(sys.path))"
          echo "=== Installed packages ==="
          pip list | grep kryptos
          echo "=== Directory structure ==="
          ls -la src/kryptos/
          ls -la src/kryptos/agents/
          echo "=== Trying import ==="
          python -c "import kryptos; print('kryptos OK'); import kryptos.agents; print('kryptos.agents OK')"
      - name: Verify package installation
        run: |
          python -c "from kryptos.agents import OpsAgent, QAgent, SpyAgent; print('✓ Agents imported successfully')"
      - name: Run fast tests (skip slow Monte Carlo tests)
        run: pytest -m "not slow" -q
